# Generated by Django 5.1.6 on 2025-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='color_1',
            field=models.CharField(default='#ffffff'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='color_2',
            field=models.CharField(default='#000000'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='picture',
            field=models.IntegerField(default=0),
        ),
    ]
