# Generated by Django 5.1.5 on 2025-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='is_launched',
            field=models.BooleanField(default=False),
        ),
    ]
