# Generated by Django 5.1.4 on 2025-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_utilisateur_friends_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
