# Generated by Django 5.1.4 on 2025-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_utilisateur_last_seen_utilisateur_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
