# Generated by Django 5.1.4 on 2025-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_utilisateur_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_online',
            field=models.BooleanField(default=0),
        ),
    ]
