# Generated by Django 5.1.6 on 2025-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_utilisateur_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
