# Generated by Django 5.1.5 on 2025-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='picture',
            field=models.CharField(default='alien'),
        ),
    ]
