# Generated by Django 4.2.11 on 2025-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_utilisateur_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='color_1',
            field=models.CharField(default='#ffffff'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='color_2',
            field=models.CharField(default='#000000'),
        ),
    ]
