# Generated by Django 4.2.11 on 2025-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_utilisateur_color_1_utilisateur_color_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='picture',
            field=models.IntegerField(default=0),
        ),
    ]
